# tasks file for prometheus-config
---
- name: Ensure prometheus user exists
  user:
    name: "{{ prometheus_user }}"
    shell: /bin/false
    system: yes
    create_home: no

- name: Download Prometheus tarball
  get_url:
    url: "{{ download_url }}"
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus archive
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Create installation directory
  file:
    path: "{{ install_dir }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"

- name: Copy Prometheus binary
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
    dest: "{{ install_dir }}/prometheus"
    mode: '0755'
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"

- name: Copy Prometheus config
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus.yml"
    dest: "{{ install_dir }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"

- name: Create data directory
  file:
    path: "{{ install_dir }}/data"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"

- name: Create systemd service file
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: '0644'

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start Prometheus
  systemd:
    name: prometheus
    enabled: yes
    state: started

