---
- name: Install and configure Prometheus on RedHat Linux Server
  hosts: localhost
  become: yes
  vars:
    prometheus_version: "3.4.1"
    prometheus_user: prometheus
    prometheus_group: prometheus
    install_dir: /opt/prometheus
    download_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
  tasks:
    - name: Ensure prometheus user exists
      user:
        name: "{{ prometheus_user }}"
        shell: /bin/false
        system: yes
        create_home: no

    - name: Download Prometheus tarball
      get_url:
        url: "{{ download_url }}"
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus archive
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Create installation directory
      file:
        path: "{{ install_dir }}"
        state: directory
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"

    - name: Copy Prometheus binaries
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
        dest: "{{ install_dir }}/prometheus"
        mode: '0755'
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"

    - name: Copy Prometheus config
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus.yml"
        dest: "{{ install_dir }}/prometheus.yml"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"

    - name: Create data directory
      file:
        path: "{{ install_dir }}/data"
        state: directory
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"

    - name: Create systemd service file for Prometheus
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus Monitoring
          Wants=network-online.target
          After=network-online.target

          [Service]
          User={{ prometheus_user }}
          Group={{ prometheus_group }}
          Type=simple
          ExecStart={{ install_dir }}/prometheus \
            --config.file={{ install_dir }}/prometheus.yml \
            --storage.tsdb.path={{ install_dir }}/data
          Restart=on-failure
          [Install]
          WantedBy=multi-user.target
    
    - name: Reload systemd
      systemd:
        daemon_reload: yes
    - name: Enable and start Prometheus
      systemd:
        name: prometheus
        enabled: yes
        state: started
