---
- name: Download CloudWatch Agent deb package
  ansible.builtin.get_url:
    url: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
    dest: /tmp/amazon-cloudwatch-agent.deb
    mode: "0644"

- name: Install CloudWatch Agent
  ansible.builtin.apt:
    deb: /tmp/amazon-cloudwatch-agent.deb
    state: present

