---
# handlers file for CA-Agent-Role
- name: Restart CloudWatch Agent
  ansible.builtin.command: >
    /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl
    -a fetch-config
    -m ec2
    -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
    -s
  changed_when: true

