---
# handlers file for cwatch-exporter
- name: reload systemd
  command: systemctl daemon-reload
  become: yes
- name: restart cloudwatch_exporter
  systemd:
    name: cloudwatch-exporter
    state: restarted
  become: yes
