---
- name: Download CloudWatch Agent DEB package
  ansible.builtin.get_url:
    url: "{{ cloudwatch_agent.deb.url }}"
    dest: "{{ cloudwatch_agent.deb.path }}"
    mode: "0644"

- name: Install CloudWatch Agent
  ansible.builtin.apt:
    deb: "{{ cloudwatch_agent.deb.path }}"
    state: present
