---
- name: Download CloudWatch Agent RPM
  ansible.builtin.get_url:
    url: "{{ cloudwatch_agent.rpm.url }}"
    dest: "{{ cloudwatch_agent.rpm.path }}"
    mode: "0644"

- name: Install CloudWatch Agent
  ansible.builtin.yum:
    name: "{{ cloudwatch_agent.rpm.path }}"
    state: present
